env:
  name: Kangaroo
  rules_and_mechanics:
    - "The player can move left/right and jump only when on a platform."
    - "The player climbs up ladders to reach the platform above."
scene:
  width: 160
  height: 210
  player:
    width: 8
    height: 24
  object_groups:
    - type: ladder
      width: 8
      height: 35
      objects:
        - x: 109
          y: 32
        - x: 16
          y: 80
        - x: 109
          y: 128
    - type: platform
      width: 128
      height: 4
      objects:
        - x: 16
          y: 28
        - x: 16
          y: 76
        - x: 16
          y: 124
        - x: 16
          y: 172
    - type: monkey
      width: 6
      height: 15
    - type: thrown coconut
      width: 2
      height: 3
predicates:
  - name: "left_of_ladder"
    object_types:
    - ladder
    description: "left of"
    action: go right
    purpose: go right to reach the ladder
  - name: "right_of_ladder"
    object_types:
    - ladder
    description: "right of"
    action: go left
    purpose: go left to reach the ladder
  - name: "on_ladder"
    object_types:
    - ladder
    description: "on"
    action: go up
    purpose: climb up the ladder
  - name: "close_by_monkey"
    object_types:
    - monkey
    description: "close by"
    action: throw punches
    purpose: throw punches at the monkey
  - name: "close_by_throwncoconut"
    object_types:
    - thrown coconut
    description: "close by"
    action: dodge
    purpose: dodge the thrown coconut